services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rbmq
    ports:
      - "5672:5672"
      - "15672:15672" # management UI
      - "15692:15692" # Prometheus metrics
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    command: >
      bash -lc "rabbitmq-plugins enable --offline rabbitmq_prometheus && exec rabbitmq-server"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./internal/metrics/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - rabbitmq
      - consumer

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000" # Grafana UI
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin123"
    volumes:
      - ./etc/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./etc/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./etc/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana-storage:/var/lib/grafana
  
  consumer:
    build:
      context: .
      dockerfile: cmd/consumer/Dockerfile
    env_file:
      - .env
    ports:
      - "2112"
    depends_on:
      - rabbitmq
    deploy:
      replicas: ${CONSUMER_REPLICAS:-3}
      resources:
        limits:
          memory: 256m

  producer:
    build:
      context: .
      dockerfile: cmd/producer/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq

volumes:
  grafana-storage:
