global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "consumer"
    static_configs:
      - targets: ["consumer:2112"]
  - job_name: "rabbitmq"
    metrics_path: /metrics/detailed
    params:
      family: [queue_coarse_metrics, queue_consumer_count]
    static_configs:
      - targets: ["rbmq:15692"]
